name: Cleanup Expired Tokens

on:
  schedule:
    # Menjalankan setiap 15 menit
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "AllJrLwrs"
          git config --global user.email "aldibayusp12@gmail.com"

      - name: Clean up expired tokens
        env:
          GH_TOKEN: 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
        run: |
          # Baca file tokens.json
          if [ -f tokens.json ]; then
            echo "File tokens.json ditemukan. Melanjutkan proses..."
          else
            echo "File tokens.json tidak ditemukan. Menghentikan proses..."
            exit 0
          fi

          # Filter token yang masih berlaku (kurang dari 60 menit)
          current_time=$(date +%s)
          jq '[.[] | select((current_time - (.timestamp | fromdateiso8601 | todate +%s)) < 3600)]' tokens.json > temp.json

          # Periksa apakah ada perubahan pada file
          if cmp -s tokens.json temp.json; then
            echo "Tidak ada perubahan. Token valid akan disimpan."
          else
            # Pindahkan kembali hasil filtering ke `tokens.json`
            mv temp.json tokens.json
            git add tokens.json
            git commit -m "Cleanup expired tokens"
            git push https://x-access-token:${GH_TOKEN}@github.com/AllJrLwrs/AllJrLwrs.git HEAD:main
          fi
