name: Cleanup Tokens

on:
  schedule:
    - cron: "*/10 * * * *" # Jalankan setiap 10 menit
  workflow_dispatch: # Memungkinkan pemicu manual

jobs:
  cleanup_tokens:
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Checkout repositori
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Langkah 2: Install PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      # Langkah 3: Jalankan script PHP untuk membersihkan token
      - name: Run Cleanup Script
        run: php cleanup_tokens.php

      # Langkah 4: Commit perubahan jika ada
- name: Commit Changes
  env:
    GH_TOKEN: ${{"secrets.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"}}
  run: |
    git config --global user.name "AllJrLwrs"
    git config --global user.email "aldibayusp12@github.com"
    git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
    git add tokens.json
    git commit -m "Cleanup expired tokens" || echo "No changes to commit"
    git push origin HEAD:${{ github.ref_name }}
