name: Send Token and Save to GitHub

on:
  schedule:
    - cron: "0 6 * * *"  # Menjalankan workflow setiap jam 6 pagi UTC
  workflow_dispatch:  # Menyediakan opsi untuk menjalankan workflow secara manual

jobs:
  send-token:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests python-telegram-bot

    - name: Run send token script
      run: |
        python send_token.py
      env:
        API_TOKEN: ${{ secrets.API_TOKEN }}
        GROUP_CHAT_ID: ${{ secrets.GROUP_CHAT_ID }}
        TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
